#!/usr/bin/env bash

set -euo pipefail

buildargs=(
  --option 'extra-substituters' 'https://colemickens.cachix.org https://nixpkgs-wayland.cachix.org https://arm.cachix.org https://thefloweringash-armv7.cachix.org'
  --option 'extra-trusted-public-keys' 'colemickens.cachix.org-1:bNrJ6FfMREB4bd4BOjEN85Niu8VcPdQe4F4KxVsb/I4= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= arm.cachix.org-1:5BZ2kjoL1q6nWhlnrbAl+G7ThY7+HaBRD9PZzqZkbnM= thefloweringash-armv7.cachix.org-1:v+5yzBD2odFKeXbmC+OPWVqx4WVoIVO6UXgnSAWFtso='
  --option 'build-cores' '0'
  --option 'narinfo-cache-negative-ttl' '0'
)

if [[ "${1:-""}" == "__init" ]]; then
  cat << EOF | "${0}"
git config --global user.name 'Cole Botkens'
git config --global user.email 'cole.mickens+colebot@gmail.com'
git remote update
EOF
  exit
elif [[ "${1-:""}" != "" ]] && [[ "${1-:""}" != ":" ]]; then
  nix-shell --pure "${buildargs[@]}" \
    --keep GITHUB_ACTION \
    --keep CI_JOB_ID \
    --keep CACHIX_SIGNING_KEY \
    --run "$(printf '\"%s\" ' "${@}")"
  exit
else
  #cat <(printf "set -x\n set -euo pipefail\n") /dev/stdin | \
  cat /dev/stdin | \
    nix-shell --pure "${buildargs[@]}" \
      --keep GITHUB_ACTION \
      --keep CI_JOB_ID \
      --keep CACHIX_SIGNING_KEY \
      --run "bash --noprofile --norc -eo pipefail </dev/stdin"
  exit
fi
