#!/usr/bin/env bash

set -euo pipefail

buildargs=(
  --option 'extra-substituters' 'https://colemickens.cachix.org https://nixpkgs-wayland.cachix.org https://arm.cachix.org https://thefloweringash-armv7.cachix.org'
  --option 'extra-trusted-public-keys' 'colemickens.cachix.org-1:bNrJ6FfMREB4bd4BOjEN85Niu8VcPdQe4F4KxVsb/I4= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= arm.cachix.org-1:5BZ2kjoL1q6nWhlnrbAl+G7ThY7+HaBRD9PZzqZkbnM= thefloweringash-armv7.cachix.org-1:v+5yzBD2odFKeXbmC+OPWVqx4WVoIVO6UXgnSAWFtso='
  --option 'build-cores' '0'
  --option 'narinfo-cache-negative-ttl' '0'
  --builders 'ssh-ng://cole@porty.ts.r10e.tech x86_64-linux - - - - big-parallel; ssh-ng://cole@orchard.ts.r10e.tech aarch64-linux'
)
nixargs=(--experimental-features "nix-command flakes") #ca-references ca-derivations recursive-nix")

if [[ "${1:-""}" == "__init" ]]; then
  cat << EOF | "${0}"
git config --global user.name 'Cole Botkens'
git config --global user.email 'cole.mickens+colebot@gmail.com'
git remote update

mkdir -p ~/.ssh
echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9YAN+P0umXeSP/Cgd5ZvoD5gpmkdcrOjmHdonvBbptbMUbI/Zm0WahBDK0jO5vfJ/C6A1ci4quMGCRh98LRoFKFRoWdwlGFcFYcLkuG/AbE8ObNLHUxAwqrdNfIV6z0+zYi3XwVjxrEqyJ/auZRZ4JDDBha2y6Wpru8v9yg41ogeKDPgHwKOf/CKX77gCVnvkXiG5ltcEZAamEitSS8Mv8Rg/JfsUUwULb6yYGh+H6RECKriUAl9M+V11SOfv8MAdkXlYRrcqqwuDAheKxNGHEoGLBk+Fm+orRChckW1QcP89x6ioxpjN9VbJV0JARF+GgHObvvV+dGHZZL1N3jr8WtpHeJWxHPdBgTupDIA5HeL0OCoxgSyyfJncMl8odCyUqE+lqXVz+oURGeRxnIbgJ07dNnX6rFWRgQKrmdV4lt1i1F5Uux9IooYs/42sKKMUQZuBLTN4UzipPQM/DyDO01F0pdcaPEcIO+tp2U6gVytjHhZqEeqAMaUbq7a6ucAuYzczGZvkApc85nIo9jjW+4cfKZqV8BQfJM1YnflhAAplIq6b4Tzayvw1DLXd2c5rae+GlVCsVgpmOFyT6bftSon/HfxwBE4wKFYF7fo7/j6UbAeXwLafDhX+S5zSNR6so1epYlwcMLshXqyJePJNhtsRhpGLd9M3UqyGDAFoOQ== cardno:7126708'  >> ~/.ssh/authorized_keys
chmod og-rw ~/

ssh-keyscan -H porty.ts.r10e.tech >> ~/.ssh/known_hosts
ssh-keyscan -H rpifour1.ts.r10e.tech >> ~/.ssh/known_hosts
EOF
  exit
elif [[ "${1:-""}" == "__nix" ]]; then
  shift
  command nix "${nixargs[@]}" "${buildargs[@]}" "${@}"
elif [[ "${1-:""}" != "" ]] && [[ "${1-:""}" != ":" ]]; then
  nix-shell --pure "${buildargs[@]}" \
    --keep NIXUP_SECRETS \
    --run "$(printf '\"%s\" ' "${@}")"
  exit
else
  #cat <(printf "set -x\n set -euo pipefail\n") /dev/stdin | \
  cat /dev/stdin | \
    nix-shell --pure "${buildargs[@]}" \
      --keep NIXUP_SECRETS \
      --run "bash --noprofile --norc -eo pipefail </dev/stdin"
  exit
fi
