#!/usr/bin/env bash

set -x
set -euo pipefail

nixargs=(--experimental-features "nix-command flakes") #ca-references ca-derivations recursive-nix")
buildargs=(
  --option 'extra-substituters' 'https://colemickens.cachix.org https://nixpkgs-wayland.cachix.org https://arm.cachix.org https://thefloweringash-armv7.cachix.org'
  --option 'extra-trusted-public-keys' 'colemickens.cachix.org-1:bNrJ6FfMREB4bd4BOjEN85Niu8VcPdQe4F4KxVsb/I4= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= arm.cachix.org-1:5BZ2kjoL1q6nWhlnrbAl+G7ThY7+HaBRD9PZzqZkbnM= thefloweringash-armv7.cachix.org-1:v+5yzBD2odFKeXbmC+OPWVqx4WVoIVO6UXgnSAWFtso='
  --option 'build-cores' '0'
  --option 'narinfo-cache-negative-ttl' '0'
  --builders-use-substitutes
)

nix "${nixargs[@]}" --version

# background it!
secrets_out="$(mktemp -d)"
nix "${nixargs[@]}" build "${buildargs[@]}" --out-link "${secrets_out}/result" '.#secrets' &
nixpid="$!"

# enable SSHD
mkdir -p ~/.ssh
chmod og-rw ~/
>>~/.ssh/authorized_keys echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9YAN+P0umXeSP/Cgd5ZvoD5gpmkdcrOjmHdonvBbptbMUbI/Zm0WahBDK0jO5vfJ/C6A1ci4quMGCRh98LRoFKFRoWdwlGFcFYcLkuG/AbE8ObNLHUxAwqrdNfIV6z0+zYi3XwVjxrEqyJ/auZRZ4JDDBha2y6Wpru8v9yg41ogeKDPgHwKOf/CKX77gCVnvkXiG5ltcEZAamEitSS8Mv8Rg/JfsUUwULb6yYGh+H6RECKriUAl9M+V11SOfv8MAdkXlYRrcqqwuDAheKxNGHEoGLBk+Fm+orRChckW1QcP89x6ioxpjN9VbJV0JARF+GgHObvvV+dGHZZL1N3jr8WtpHeJWxHPdBgTupDIA5HeL0OCoxgSyyfJncMl8odCyUqE+lqXVz+oURGeRxnIbgJ07dNnX6rFWRgQKrmdV4lt1i1F5Uux9IooYs/42sKKMUQZuBLTN4UzipPQM/DyDO01F0pdcaPEcIO+tp2U6gVytjHhZqEeqAMaUbq7a6ucAuYzczGZvkApc85nIo9jjW+4cfKZqV8BQfJM1YnflhAAplIq6b4Tzayvw1DLXd2c5rae+GlVCsVgpmOFyT6bftSon/HfxwBE4wKFYF7fo7/j6UbAeXwLafDhX+S5zSNR6so1epYlwcMLshXqyJePJNhtsRhpGLd9M3UqyGDAFoOQ== cardno:7126708"

# activate secrets
# TODO: should this just include the entire HM config?
mkdir -p ~/.config/sops/age/
set +x;
printf "%s" "${SOPS_AGE_KEY}" > ~/.config/sops/age/keys.txt
set -x;

sudo groupadd keys
sudo gpasswd --add "${USER}" keys

# instead of &/wait pid, just run the nix build again and wait for both
wait ${nixpid}
# this caused some weird internal nix issue???????? wtf?
#nix "${nixargs[@]}" build "${buildargs[@]}" --out-link "${secrets_out}/result" '.#secrets'
sudo "${secrets_out}/result"

set +x;
source /run/secrets/nixup-secrets;
echo "::set-output name=TAILSCALE_AUTHKEY::${TAILSCALE_AUTHKEY}"
set -x
