name: "nixcfg-next"
concurrency: "nixcfg-next"
on:
  schedule:
    - cron: '37 * * * *'
  workflow_dispatch:
jobs:
  "update":
    permissions:
      id-token: "write"
      contents: "write"
    runs-on: "ubuntu-24.04"
    outputs:
      next_git_ref: ${{ steps.update.outputs.next_git_ref }}
    steps:
    - name: checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: main
    - uses: "DeterminateSystems/determinate-nix-action@main"
    - uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: prep
      run: nix shell nixpkgs#jujutsu -c ./.github/prep.sh
    - name: update
      id: update
      run: nix shell nixpkgs#jujutsu -c ./.github/update.sh
  "builds":
    needs: "update"
    uses: ./.github/workflows/build.yaml
    with:
      git_ref: ${{needs.update.outputs.next_git_ref}}
      key: main-next-wip
  "risky":
    needs: "update"
    uses: ./.github/workflows/risky.yaml
    with:
      git_ref: ${{needs.update.outputs.next_git_ref}}
      key: main-next-wip
