name: "nixcfg-risky"
concurrency: "nixcfg-risky"
on:
  push:
    branches:
      - "main"
jobs:
  "builds":
    permissions:
      id-token: "write"
      contents: "read"
    strategy:
      fail-fast: false
      matrix:
        runner:
        - "ubuntu-24.04"
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: "DeterminateSystems/determinate-nix-action@main"
    - uses: "DeterminateSystems/magic-nix-cache-action@main"
    - name: build + cache (jupitertwo)
      if: success() || failure()
      run: |
        nix build -L --keep-going \
          .#toplevels.jupitertwo
    - name: build + cache (jupitertwo) (dump)
      if: success() || failure()
      run: |
        x="$(nix eval --raw .#toplevels.jupitertwo)"
        echo $x
        nix-store -q --graph $x
    - name: build + cache (riscv64 installer)
      if: success() || failure()
      run: |
        nix build -L --keep-going \
          .#extra.riscv64-linux.installer
    - name: build + cache (riscv64 iso bits)
      if: success() || failure()
      run: |
        nix build -L --keep-going \
          .#extra.riscv64-linux.installer-sdimage-bits
