name: "nixcfg-test"
concurrency: "nixcfg-test"
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0/20 * * * *'
  # push:
  #   branches:
  #     - "main"
jobs:
  "test":
    runs-on: "slynux-nixcfg-default"
    steps:
    - name: next
      run: |
        set -x
        echo $STATE_DIRECTORY >&2
        echo $RUNTIME_DIRECTORY >&2
        echo $LOGS_DIRECTORY >&2
