# v4
creation_rules:
  - path_regex: .*$
    key_groups:
      - pgp: [  8A94ED58A476A13AE0D6E85E9758078DE5308308, ]
        age: [  age13kughael3jqxry5wkc62cutysm9h9lvswsu7zkrml98m3y6625esl5ke7u,  age15pfzj764rps90cp9y23plctcpgtsyndtcf05gd2xcj8r224tng5qmj3hyg,  age17jn9szrg49cxlz5hu7lsvcjtdevxjrqfjflacevypgasdqjd4elq3xnyy7, ]
