# v4
creation_rules:
  - path_regex: .*$
    key_groups:
      - pgp: [  8A94ED58A476A13AE0D6E85E9758078DE5308308, ]
        age: [  age1en4chc0kp9fstf88h6m7x3fz2ngc6yusg98w26ymp7rgctkxsd3qz6x299,  age15pfzj764rps90cp9y23plctcpgtsyndtcf05gd2xcj8r224tng5qmj3hyg,  age1ahmrnqpyv8v3vknenl29lyzmgjwvv6cw9ss27vmgm4ftt7wyfg0s4vyp3v,  age17jn9szrg49cxlz5hu7lsvcjtdevxjrqfjflacevypgasdqjd4elq3xnyy7, ]
